#!/usr/bin/env python3
"""Rebuild the deterministic strategy fixtures after a copy or logic change.

These are byte-for-byte snapshots of what the builders produce. They are cheap:
no model, no human, no review. They were being regenerated by hand, which is why
a one-line copy edit used to feel like it needed a ceremony.

The expensive artifacts are deliberately not here. Blind-reviewer packets need two
independent model runs each (`scripts/blind_review.py`), the source audit needs an
isolated review, and the visual goldens need a human to look at a screenshot. Those
are release evidence and only bind under FM_RELEASE_EVIDENCE=1.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from found_money.map import build_thin_slice_money_map  # noqa: E402
from found_money.strategy import build_canonical_saas_recovery_strategy  # noqa: E402

FM026 = ROOT / "tests/fixtures/saas/strategy/fm026"


def main() -> int:
    run = build_canonical_saas_recovery_strategy(
        build_thin_slice_money_map(run_id="run_fm026_fixture")
    )
    written = []
    for name, payload in (
        ("grounded-evidence.json", run.packet),
        ("recovery-plays.json", run.recovery_plays),
        ("strategy-audit-receipt.json", run.receipt),
        ("differentiation-report.json", run.differentiation),
    ):
        path = FM026 / name
        payload_bytes = payload.to_canonical_json()
        if path.read_bytes() != payload_bytes:
            path.write_bytes(payload_bytes)
            written.append(name)
    # The provider receipt binds the evidence schema, so contract changes also
    # require this deterministic replay. This is not reviewer certification.
    from found_money.contracts.strategy import StrategyBusinessProfileV1
    from found_money.strategy.boundary import FixtureGroundedStrategyProvider, run_strategy_boundary

    provider = FixtureGroundedStrategyProvider()
    replay = run_strategy_boundary(
        build_thin_slice_money_map(run_id="run_fm025_fixture"),
        StrategyBusinessProfileV1(
            product="Annual subscription",
            proof="Three approved case studies",
            margin="40 percent contribution margin",
            channel="email",
            capacity="100 recovery reviews per week",
            destination="billing portal",
        ),
        provider,
        configured_model_id=provider.configured_model_id,
    ).boundary.receipt.to_canonical_json()
    receipt_path = ROOT / "tests/fixtures/saas/strategy/grounded_receipt.json"
    if receipt_path.read_bytes() != replay:
        receipt_path.write_bytes(replay)
        written.append("grounded_receipt.json")
    if written:
        print(f"regen: rewrote {len(written)} fixture(s): {', '.join(written)}")
    else:
        print("regen: fixtures already match the builders")
    print(
        "regen: reviewer packets, the source audit and the visual goldens are "
        "release evidence and are not regenerated here"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
